### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by screendriver** [nielsmaerten/cerebro-emojione#1]
I installed the plugin but it seems not to work on my machine. I type `emoj i like cookies` like in the example but nothing happens. All other plugins I installed into `cerebro` work fine.

I am using Manjaro Linux and the latest version of cerebro.

**Comment by nielsmaerten** [comment]
Hi @screendriver 

You're right! I published this plugin before I had fully tested it.  
(A clear rookie mistake of someone starting out with open-source. My bad!)

But I managed to find the bug:  
Babili minification messed up the module signature, which prevented the plugin from loading.  
I switched to babel for compilation, and published the bugfix as version 0.1.2.

Should work smoothly now!

**Comment by screendriver** [comment]
Thank you. It's working now 😎
